/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sports_Project;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class add_staff extends javax.swing.JFrame {

    /**
     * Creates new form add_staff
     */
    public add_staff() {
        this.setResizable(false);
        initComponents();
        Toolkit tk=Toolkit.getDefaultToolkit();
                int xsize=990;
                int ysize=930;
                this.setSize(xsize,ysize);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        sal = new javax.swing.JTextField();
        staff_id = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        csports = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        contact = new javax.swing.JTextField();
        staff_type = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("     ADD STAFF");
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 0));
        jLabel2.setText("        HYDRA SPORTS ACADEMY");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(5, 5, 929, 92);

        jLabel1.setBackground(new java.awt.Color(255, 51, 153));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText(" STAFF :-");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 100, 480, 78);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("HOME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(630, 120, 89, 31);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("LOGOUT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(811, 120, 123, 31);

        jLabel14.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 0));
        jLabel14.setText("ENTER MEMBER NAME                         :");
        jLabel14.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jLabel14ComponentHidden(evt);
            }
        });
        jPanel1.add(jLabel14);
        jLabel14.setBounds(17, 253, 443, 51);

        jLabel15.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 0));
        jLabel15.setText("ENTER SALARY                                         :");
        jLabel15.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jLabel15ComponentHidden(evt);
            }
        });
        jPanel1.add(jLabel15);
        jLabel15.setBounds(17, 316, 443, 51);

        jLabel16.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 0));
        jLabel16.setText("ENTER DATE OF JOINING                     :");
        jLabel16.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jLabel16ComponentHidden(evt);
            }
        });
        jPanel1.add(jLabel16);
        jLabel16.setBounds(17, 379, 443, 51);

        jLabel17.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 0));
        jLabel17.setText("ENTER STAFF ID                                       :");
        jLabel17.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jLabel17ComponentHidden(evt);
            }
        });
        jPanel1.add(jLabel17);
        jLabel17.setBounds(17, 194, 443, 51);

        jLabel18.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 0));
        jLabel18.setText("ENTER ADDRESS                                     : ");
        jLabel18.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jLabel18ComponentHidden(evt);
            }
        });
        jPanel1.add(jLabel18);
        jLabel18.setBounds(17, 504, 443, 51);

        jLabel19.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 0));
        jLabel19.setText("ENTER STAFF TYPE                                 :");
        jLabel19.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jLabel19ComponentHidden(evt);
            }
        });
        jPanel1.add(jLabel19);
        jLabel19.setBounds(17, 624, 443, 51);

        jLabel20.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 0));
        jLabel20.setText("ENTER COACHING SPORT                     :");
        jLabel20.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jLabel20ComponentHidden(evt);
            }
        });
        jPanel1.add(jLabel20);
        jLabel20.setBounds(17, 687, 443, 51);

        jLabel21.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 0));
        jLabel21.setText("ENTER CONTACT NUMBER                  :");
        jLabel21.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jLabel21ComponentHidden(evt);
            }
        });
        jPanel1.add(jLabel21);
        jLabel21.setBounds(17, 442, 443, 51);

        sal.setBackground(new java.awt.Color(108, 122, 137));
        sal.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        sal.setForeground(new java.awt.Color(228, 241, 254));
        jPanel1.add(sal);
        sal.setBounds(465, 315, 402, 56);

        staff_id.setBackground(new java.awt.Color(108, 122, 137));
        staff_id.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        staff_id.setForeground(new java.awt.Color(228, 241, 254));
        jPanel1.add(staff_id);
        staff_id.setBounds(465, 189, 402, 56);

        date.setBackground(new java.awt.Color(108, 122, 137));
        date.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        date.setForeground(new java.awt.Color(228, 241, 254));
        jPanel1.add(date);
        date.setBounds(465, 378, 402, 56);

        name.setBackground(new java.awt.Color(108, 122, 137));
        name.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        name.setForeground(new java.awt.Color(228, 241, 254));
        jPanel1.add(name);
        name.setBounds(465, 252, 402, 56);

        csports.setBackground(new java.awt.Color(108, 122, 137));
        csports.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        csports.setForeground(new java.awt.Color(228, 241, 254));
        jPanel1.add(csports);
        csports.setBounds(465, 686, 405, 56);

        address.setBackground(new java.awt.Color(108, 122, 137));
        address.setColumns(20);
        address.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        address.setForeground(new java.awt.Color(228, 241, 254));
        address.setRows(5);
        address.setBorder(null);
        jScrollPane1.setViewportView(address);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(465, 504, 402, 102);

        contact.setBackground(new java.awt.Color(108, 122, 137));
        contact.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        contact.setForeground(new java.awt.Color(228, 241, 254));
        jPanel1.add(contact);
        contact.setBounds(465, 441, 402, 56);

        staff_type.setBackground(new java.awt.Color(108, 122, 137));
        staff_type.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        staff_type.setForeground(new java.awt.Color(228, 241, 254));
        jPanel1.add(staff_type);
        staff_type.setBounds(465, 623, 402, 56);

        jButton3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jButton3.setText("UPDATE STAFF");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(63, 787, 250, 47);

        jButton4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jButton4.setText("ADD STAFF");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(331, 787, 250, 47);

        jButton5.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jButton5.setText("REMOVE STAFF");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(599, 787, 251, 47);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Project images\\78.jpg")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 10, 930, 840);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 950, 860);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Sports_System SS=new Sports_System();
        SS.setVisible(true);
        SS.pack();
        SS.setLocationRelativeTo(null);
        Toolkit tk=Toolkit.getDefaultToolkit();
        int xsize=947;
        int ysize=707;
        SS.setSize(xsize,ysize);
        SS.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Login_page rgf=new Login_page();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel14ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel14ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14ComponentHidden

    private void jLabel15ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel15ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15ComponentHidden

    private void jLabel16ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel16ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16ComponentHidden

    private void jLabel17ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel17ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17ComponentHidden

    private void jLabel18ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel18ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18ComponentHidden

    private void jLabel19ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel19ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel19ComponentHidden

    private void jLabel20ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel20ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel20ComponentHidden

    private void jLabel21ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel21ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel21ComponentHidden

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String Staff_id =staff_id.getText();
        String Name=name.getText();
        int Salary=Integer.parseInt(sal.getText());
        String Date_of_joining=date.getText();
        long Contact=Long.parseLong(contact.getText());
        String Address=address.getText();
        String type=staff_type.getText();
        String Coaching_Sports=csports.getText();        
        if(Staff_id.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Staff Id");
        }
        else if(Name.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Staff Member Name");
        }
        else if(contact.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Fee of Sport");
        }
        else if(type.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Time of your sport");
        }
        try{            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/my_connection?zeroDateTimeBehavior=convertToNull","root","");
            ResultSet rs=null;
            int candidateId=0;
            String query="INSERT INTO staff values('"+Staff_id+"','"+Name+"','"+Salary+"','"+Date_of_joining+"','"+Contact+"','"+Address+"','"+type+"','"+Coaching_Sports+"')";
            Statement st=con.createStatement();
            int rowAffected=st.executeUpdate(query);
            JOptionPane.showMessageDialog(null,Name+" Staff Member Added");
            staff_id.setText(" ");
            name.setText(" ");
            sal.setText(" ");
            date.setText(" "); 
            contact.setText(" ");
            address.setText(" ");
            staff_type.setText(" ");
            csports.setText(" ");             
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Error"+ex); 
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String Staff_id =staff_id.getText();
        String Name=name.getText();
        int Salary=Integer.parseInt(sal.getText());
        String Date_of_joining=date.getText();
        long Contact=Long.parseLong(contact.getText());
        String Address=address.getText();
        String type=staff_type.getText();
        String Coaching_Sports=csports.getText();        
        if(Staff_id.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Staff Id");
        }
        else if(Name.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Staff Member Name");
        }
        else if(contact.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Fee of Sport");
        }
        else if(type.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Time of your sport");
        }
        int response=JOptionPane.showConfirmDialog(this,"Are you sure you want to delete Record","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(response==JOptionPane.YES_OPTION){
        try{            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/my_connection?zeroDateTimeBehavior=convertToNull","root","");
            ResultSet rs=null;
            int candidateId=0;
            String query="DELETE FROM staff Where(Staff_id='"+staff_id+"' AND Name='"+name+"')";
            Statement st=con.createStatement();
            int rowAffected=st.executeUpdate(query);
            JOptionPane.showMessageDialog(null,rowAffected+"New Staff Member Added");
            staff_id.setText(" ");
            name.setText(" ");
            sal.setText(" ");
            date.setText(" "); 
            contact.setText(" ");
            address.setText(" ");
            staff_type.setText(" ");
            csports.setText(" ");             
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Error"+ex); 
        }  
        }
        else if(response==JOptionPane.NO_OPTION){
            add_staff AS=new add_staff();
            AS.setVisible(true);
            AS.pack();
            AS.setLocationRelativeTo(null);
            Toolkit tk=Toolkit.getDefaultToolkit();
                int xsize=990;
                int ysize=930;
                AS.setSize(xsize,ysize);
            AS.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();     
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String Staff_id =staff_id.getText();
        String Name=name.getText();
        int Salary=Integer.parseInt(sal.getText());
        String Date_of_joining=date.getText();
        long Contact=Long.parseLong(contact.getText());
        String Address=address.getText();
        String type=staff_type.getText();
        String Coaching_Sports=csports.getText();        
        if(Staff_id.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Staff Id");
        }
        else if(Name.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Staff Member Name");
        }
        else if(contact.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Fee of Sport");
        }
        else if(type.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Time of your sport");
        }
        int response=JOptionPane.showConfirmDialog(this,"Are you sure you want to update Record","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(response==JOptionPane.YES_OPTION){
        try{            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/my_connection?zeroDateTimeBehavior=convertToNull","root","");
            ResultSet rs=null;
            int candidateId=0;
            String query="UPDATE staff SET('Staff_id'='"+Staff_id+"','Name'='"+Name+"','Salary'='"+Salary+"','Date_of_joining'='"+Date_of_joining+"','Contact'='"+Contact+"','Address'='"+Address+"','type'='"+type+"','Coaching_Sports'='"+Coaching_Sports+"')";
            Statement st=con.createStatement();
            int rowAffected=st.executeUpdate(query);
            JOptionPane.showMessageDialog(null,rowAffected+"New Staff Member Added");
            staff_id.setText(" ");
            name.setText(" ");
            sal.setText(" ");
            date.setText(" "); 
            contact.setText(" ");
            address.setText(" ");
            staff_type.setText(" ");
            csports.setText(" ");             
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Error"+ex); 
        }}
        else if(response==JOptionPane.NO_OPTION){
            add_staff AS=new add_staff();
            AS.setVisible(true);
            AS.pack();
            AS.setLocationRelativeTo(null);
            Toolkit tk=Toolkit.getDefaultToolkit();
                int xsize=990;
                int ysize=930;
                AS.setSize(xsize,ysize);
            AS.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();     
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_staff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField csports;
    private javax.swing.JTextField date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField sal;
    private javax.swing.JTextField staff_id;
    private javax.swing.JTextField staff_type;
    // End of variables declaration//GEN-END:variables
}
