/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sports_Project;

/**
 *
 * @author user
 */

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class add_prizes extends javax.swing.JFrame {

    /**
     * Creates new form add_prizes
     */
    public add_prizes() {
        this.setResizable(false);
        this.setVisible(true);
        initComponents();
        Toolkit tk=Toolkit.getDefaultToolkit();
                int xsize=900;
                int ysize=720;
                this.setSize(xsize,ysize);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        title = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        SName = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        pos = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("     ADD PRIZE");
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("    HYDRA SPORTS ACADEMY");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(5, 5, 813, 92);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("  PRIZES :-");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(5, 104, 406, 78);

        jLabel17.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("ENTER PRIZE TITLE                        :");
        jLabel17.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jLabel17ComponentHidden(evt);
            }
        });
        jPanel1.add(jLabel17);
        jLabel17.setBounds(17, 250, 394, 51);

        jLabel18.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setText("ENTER PLAYER/TEAM ID             :");
        jLabel18.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jLabel18ComponentHidden(evt);
            }
        });
        jPanel1.add(jLabel18);
        jLabel18.setBounds(17, 313, 394, 51);

        jLabel19.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("ENTER DATE                                    :");
        jLabel19.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jLabel19ComponentHidden(evt);
            }
        });
        jPanel1.add(jLabel19);
        jLabel19.setBounds(17, 190, 394, 51);

        jLabel20.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("ENTER SPORTS NAME                 :");
        jLabel20.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jLabel20ComponentHidden(evt);
            }
        });
        jPanel1.add(jLabel20);
        jLabel20.setBounds(17, 439, 394, 51);

        jLabel21.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jLabel21.setText("ENTER POSITION                          :");
        jLabel21.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jLabel21ComponentHidden(evt);
            }
        });
        jPanel1.add(jLabel21);
        jLabel21.setBounds(17, 502, 394, 51);

        jLabel22.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setText("ENTER PLAYER/TEAM NAME     :");
        jLabel22.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jLabel22ComponentHidden(evt);
            }
        });
        jPanel1.add(jLabel22);
        jLabel22.setBounds(17, 376, 394, 51);

        title.setBackground(new java.awt.Color(108, 122, 137));
        title.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        title.setForeground(new java.awt.Color(228, 241, 254));
        jPanel1.add(title);
        title.setBounds(416, 249, 402, 56);

        id.setBackground(new java.awt.Color(108, 122, 137));
        id.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        id.setForeground(new java.awt.Color(228, 241, 254));
        jPanel1.add(id);
        id.setBounds(416, 312, 402, 56);

        name.setBackground(new java.awt.Color(108, 122, 137));
        name.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        name.setForeground(new java.awt.Color(228, 241, 254));
        jPanel1.add(name);
        name.setBounds(416, 375, 402, 56);

        SName.setBackground(new java.awt.Color(108, 122, 137));
        SName.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        SName.setForeground(new java.awt.Color(228, 241, 254));
        jPanel1.add(SName);
        SName.setBounds(416, 438, 402, 56);

        date.setBackground(new java.awt.Color(108, 122, 137));
        date.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        date.setForeground(new java.awt.Color(228, 241, 254));
        jPanel1.add(date);
        date.setBounds(416, 189, 402, 56);

        pos.setBackground(new java.awt.Color(108, 122, 137));
        pos.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        pos.setForeground(new java.awt.Color(228, 241, 254));
        jPanel1.add(pos);
        pos.setBounds(416, 501, 402, 56);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("HOME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(481, 124, 89, 31);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("LOGOUT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(635, 124, 123, 31);

        jButton4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jButton4.setText("ADD PRIZE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(285, 575, 250, 47);

        jButton3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jButton3.setText("UPDATE PRIZE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(17, 575, 250, 47);

        jButton5.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jButton5.setText("REMOVE PRIZE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(561, 575, 257, 47);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Project images\\111.jpg")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 10, 840, 630);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 860, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel17ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel17ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17ComponentHidden

    private void jLabel18ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel18ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18ComponentHidden

    private void jLabel19ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel19ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel19ComponentHidden

    private void jLabel20ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel20ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel20ComponentHidden

    private void jLabel21ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel21ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel21ComponentHidden

    private void jLabel22ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel22ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel22ComponentHidden

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Sports_System SS=new Sports_System();
        SS.setVisible(true);
        SS.pack();
        SS.setLocationRelativeTo(null);
        Toolkit tk=Toolkit.getDefaultToolkit();
            int xsize=947;
            int ysize=707;
            SS.setSize(xsize,ysize);
        SS.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Login_page rgf=new Login_page();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String Date =date.getText();
        String Title=title.getText();
        String Player_id=id.getText();
        String Player_Name=name.getText();
        String Sports_Name=SName.getText();
        int Position=Integer.valueOf(pos.getText());
        if(id.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Staff Id");
        }
        else if(name.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Prize Name");
        }
        else if(pos.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Position");
        }
        else if(title.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Prize Title");
        }
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/my_connection?zeroDateTimeBehavior=convertToNull","root","");
            ResultSet rs=null;
            int candidateId=0;
            String query="INSERT INTO prizes values('"+Date+"','"+Title+"','"+Player_id+"','"+Player_Name+"','"+Sports_Name+"','"+Position+"')";
            Statement st=con.createStatement();
            int rowAffected=st.executeUpdate(query);
            JOptionPane.showMessageDialog(null,rowAffected+"New Prize Added");
            date.setText(" ");
            title.setText(" ");
            id.setText(" ");
            name.setText(" ");
            SName.setText(" ");
            pos.setText(" ");
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Error"+ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String Date =date.getText();
        String Title=title.getText();
        String Player_id=id.getText();
        String Player_Name=name.getText();
        String Sports_Name=SName.getText();
        int Position=Integer.valueOf(pos.getText());
        if(id.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Staff Id");
        }
        else if(name.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Prize Name");
        }
        else if(pos.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Position");
        }
        else if(title.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Prize Title");
        }
        int response=JOptionPane.showConfirmDialog(this,"Are you sure you want to update Record","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(response==JOptionPane.YES_OPTION){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/my_connection?zeroDateTimeBehavior=convertToNull","root","");
            ResultSet rs=null;
            int candidateId=0;
            String query="INSERT INTO prizes values('"+Date+"','"+Title+"','"+Player_id+"','"+Player_Name+"','"+Sports_Name+"','"+Position+"')";
            Statement st=con.createStatement();
            int rowAffected=st.executeUpdate(query);
            JOptionPane.showMessageDialog(null,rowAffected+"Prize Successfully Updated");
            date.setText(" ");
            title.setText(" ");
            id.setText(" ");
            name.setText(" ");
            SName.setText(" ");
            pos.setText(" ");
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Error"+ex);
        }}
            else if(response==JOptionPane.NO_OPTION){
                add_staff AS=new add_staff();
                AS.setVisible(true);
                AS.pack();
                AS.setLocationRelativeTo(null);
                Toolkit tk=Toolkit.getDefaultToolkit();
                int xsize=990;
                int ysize=930;
                AS.setSize(xsize,ysize);
                AS.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                this.dispose();
            }// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String Date =date.getText();
        String Title=title.getText();
        String Player_id=id.getText();
        String Player_Name=name.getText();
        String Sports_Name=SName.getText();
        int Position=Integer.valueOf(pos.getText());
        if(id.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Staff Id");
        }
        else if(name.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Prize Name");
        }
        else if(pos.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Position");
        }
        else if(title.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Prize Title");
        }
        int response=JOptionPane.showConfirmDialog(this,"Are you sure you want to delete Record","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(response==JOptionPane.YES_OPTION){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/my_connection?zeroDateTimeBehavior=convertToNull","root","");
            ResultSet rs=null;
            int candidateId=0;
            String query="INSERT INTO prizes values('"+Date+"','"+Title+"','"+Player_id+"','"+Player_Name+"','"+Sports_Name+"','"+Position+"')";
            Statement st=con.createStatement();
            int rowAffected=st.executeUpdate(query);
            JOptionPane.showMessageDialog(null,rowAffected+"Successfully Removed");
            date.setText(" ");
            title.setText(" ");
            id.setText(" ");
            name.setText(" ");
            SName.setText(" ");
            pos.setText(" ");
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Error"+ex);
        } }
        else if(response==JOptionPane.NO_OPTION){
            add_staff AS=new add_staff();
            AS.setVisible(true);
            AS.pack();
            AS.setLocationRelativeTo(null);
            Toolkit tk=Toolkit.getDefaultToolkit();
            int xsize=990;
            int ysize=930;
            AS.setSize(xsize,ysize);
            AS.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_prizes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_prizes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_prizes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_prizes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_prizes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SName;
    private javax.swing.JTextField date;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField pos;
    private javax.swing.JTextField title;
    // End of variables declaration//GEN-END:variables
}
