/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sports_Project;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javafx.scene.control.RadioButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Player_Registration extends javax.swing.JFrame {

    /**
     * Creates new form Player_Registration
     */
    public Player_Registration() {
       this.setResizable(false);
        initComponents();
       // Toolkit tk=Toolkit.getDefaultToolkit();
         //    int xsize=1412;
             //int ysize=940;
             this.setSize(1412,960);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        pnumber = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        addr = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("     PLAYER REGISTRATION");
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("               HYDRA SPORTS ACADEMY");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(5, 5, 1380, 92);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setText("  Player Registration :-");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(5, 104, 470, 78);

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText(" Player Id                                :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(17, 235, 338, 56);

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("ADDRESS                                :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(17, 695, 338, 56);

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("PHONE NUMBER                 :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(17, 363, 338, 56);

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("AGE                                          :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(17, 432, 344, 56);

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("GENDER                                  :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(17, 501, 344, 56);

        jComboBox1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CRICKET", "FOOTBALL", "BADMINTON", "BASKETBALL", "VOLLEYBALL", "TABLE TENNIS", "TENNIS", "ATHLETICS", "CHESS", "SHOOTING", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(373, 572, 400, 56);

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("SPORTS                                   :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(17, 570, 344, 56);

        id.setBackground(new java.awt.Color(0, 0, 0));
        id.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        id.setForeground(new java.awt.Color(228, 241, 254));
        jPanel1.add(id);
        id.setBounds(367, 237, 400, 56);

        pnumber.setBackground(new java.awt.Color(0, 0, 0));
        pnumber.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        pnumber.setForeground(new java.awt.Color(228, 241, 254));
        jPanel1.add(pnumber);
        pnumber.setBounds(367, 363, 400, 56);

        age.setBackground(new java.awt.Color(0, 0, 0));
        age.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        age.setForeground(new java.awt.Color(228, 241, 254));
        jPanel1.add(age);
        age.setBounds(366, 432, 400, 56);

        male.setBackground(new java.awt.Color(108, 122, 137));
        male.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        male.setForeground(new java.awt.Color(228, 241, 254));
        male.setText("MALE");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel1.add(male);
        male.setBounds(369, 503, 198, 56);

        female.setBackground(new java.awt.Color(108, 122, 137));
        female.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        female.setForeground(new java.awt.Color(228, 241, 254));
        female.setText("FEMALE");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel1.add(female);
        female.setBounds(585, 502, 184, 58);

        addr.setBackground(new java.awt.Color(0, 0, 0));
        addr.setColumns(20);
        addr.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        addr.setForeground(new java.awt.Color(228, 241, 254));
        addr.setRows(5);
        jScrollPane1.setViewportView(addr);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(373, 641, 400, 136);

        jButton2.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jButton2.setText("ADD RECORD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(724, 805, 291, 56);

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("YOUR NAME                         :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(17, 303, 348, 57);

        name.setBackground(new java.awt.Color(0, 0, 0));
        name.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        name.setForeground(new java.awt.Color(228, 241, 254));
        jPanel1.add(name);
        name.setBounds(367, 300, 400, 56);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("HOME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1141, 123, 89, 31);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setText("LOGOUT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(1248, 123, 123, 31);

        area.setBackground(new java.awt.Color(0, 0, 0));
        area.setColumns(20);
        area.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        area.setForeground(new java.awt.Color(255, 0, 0));
        area.setRows(5);
        jScrollPane2.setViewportView(area);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(802, 237, 569, 540);

        jButton4.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jButton4.setText("CLEAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(32, 805, 291, 56);

        jButton5.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jButton5.setText("GENERATE BILL");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(373, 805, 291, 56);

        jButton6.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jButton6.setText("PRINT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(1069, 805, 291, 56);

        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Project images\\109.jpg")); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 10, 1380, 880);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1400, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String Player_id =id.getText();
        String Name=name.getText();
        String Phone_number=pnumber.getText();
        String Age=age.getText();
        String Gender;
        if(female.isSelected()){
            Gender="Female";
        }
        else{
            Gender="Male";
        }
        
        String Sports=jComboBox1.getSelectedItem().toString();
        String Address=addr.getText();
        
        try{ 
            if(Player_id.equals("")){
                JOptionPane.showMessageDialog(null,"Enter Sports Id");
            }
            else if(Name.equals("")){
                JOptionPane.showMessageDialog(null,"Enter Sports Name");
            }
            else{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/my_connection?zeroDateTimeBehavior=convertToNull","root","");
                String query="INSERT INTO players values('"+Player_id+"','"+Name+"',"+Phone_number+","+Age+",'"+Gender+"','"+Sports+"','"+Address+"')";
                Statement st=con.createStatement();
                int rt=st.executeUpdate(query);
                if(rt==1)
                    JOptionPane.showMessageDialog(null,Name+" Registered Successfully");
       
        } 
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Error"+ex); 
        }
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Sports_System SS=new Sports_System();
        SS.setVisible(true);
        SS.pack();
        SS.setLocationRelativeTo(null);
        Toolkit tk=Toolkit.getDefaultToolkit();
            int xsize=947;
            int ysize=707;
            SS.setSize(xsize,ysize);
        SS.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Login_page rgf=new Login_page();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        Toolkit tk=Toolkit.getDefaultToolkit();
                int xsize=910;
                int ysize=715;
                rgf.setSize(xsize,ysize);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
        if(female.isSelected()){
            female.setSelected(false);
        }
    }//GEN-LAST:event_maleActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
            if(male.isSelected()){
                male.setSelected(false);
            }
// TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            id.setText(" ");
            name.setText(" ");
            pnumber.setText(" ");
            age.setText(" ");
            addr.setText(" ");
            name.setText(" ");  
            area.setText(" ");          // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        area.setText("**************************************\n");
        area.setText(area.getText()+"*               Receipt             *\n");
        area.setText(area.getText()+"**************************************\n");
        String Gender;
        if(female.isSelected()){
            Gender="Female";
        }
        else{
            Gender="Male";
        }
        int amount=0;
        Object SelectedItem=jComboBox1.getSelectedItem().toString();
        if (SelectedItem == "CRICKET"){
            amount=2000;
        }
        else if (SelectedItem == "FOOTBALL"){
            amount=2500;
        }
        else if (SelectedItem == "FOOTBALL"){
            amount=2500;
        }
        else if (SelectedItem == "TABLE TENNIS"){
            amount=1600;
        }
        else if (SelectedItem == "TENNIS"){
            amount=1600;
        }
        else if (SelectedItem == "VOLLEYBALL"){
            amount=1800;
        }
        else if (SelectedItem == "BASKETBALL"){
            amount=1800;
        }
        else if (SelectedItem == "BADMINTON"){
            amount=1800;
        }
        Date obj=new Date();
        String date=obj.toString();
        area.setText(area.getText()+"\n"+date+"\n\n");
        area.setText(area.getText()+"Player ID      : "+id.getText()+"\n");
        area.setText(area.getText()+"Player Name    : "+name.getText()+"\n");
        area.setText(area.getText()+"Phone number   : "+pnumber.getText()+"\n");
        area.setText(area.getText()+"Player Age     : "+age.getText()+"\n");
        area.setText(area.getText()+"Player Gender  : "+Gender+"\n");
        area.setText(area.getText()+"Player Sport   : "+jComboBox1.getSelectedItem().toString()+"\n");
        area.setText(area.getText()+"Sport Charge   : "+amount+"\n");
        area.setText(area.getText()+"Player Address : "+addr.getText()+"\n\n");
        area.setText(area.getText()+"\n                                               Signature");
// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        try{
           area.print(); 
        }
        catch(Exception ex){
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Player_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Player_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Player_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Player_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Player_Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addr;
    private javax.swing.JTextField age;
    private javax.swing.JTextArea area;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField name;
    private javax.swing.JTextField pnumber;
    // End of variables declaration//GEN-END:variables
}
