/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sports_Project;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class RegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        this.setResizable(false);
        initComponents();
        Toolkit tk=Toolkit.getDefaultToolkit();
                int xsize=875;
                int ysize=728;
                this.setSize(xsize,ysize);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        first = new javax.swing.JTextField();
        last = new javax.swing.JTextField();
        user = new javax.swing.JTextField();
        repassword = new javax.swing.JPasswordField();
        password = new javax.swing.JPasswordField();
        chek = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("     REGISTER PAGE");
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 0));
        jLabel7.setText("     HYDRA SPORTS ACADEMY");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(5, 5, 860, 92);

        jButton4.setBackground(new java.awt.Color(255, 102, 102));
        jButton4.setFont(new java.awt.Font("Vijaya", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 0, 0));
        jButton4.setText("CANCEL");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(100, 460, 201, 66);

        jButton3.setBackground(new java.awt.Color(153, 153, 255));
        jButton3.setFont(new java.awt.Font("Vijaya", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 204));
        jButton3.setText("REGISTER");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(500, 460, 201, 66);

        jLabel14.setFont(new java.awt.Font("Utsaah", 3, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 255, 204));
        jLabel14.setText("            CLICK HERE TO LOGIN");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel14);
        jLabel14.setBounds(180, 570, 440, 49);

        jLabel4.setFont(new java.awt.Font("Vrinda", 1, 30)); // NOI18N
        jLabel4.setText("RE-PASSWORD       : ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 350, 310, 50);

        jLabel5.setFont(new java.awt.Font("Vrinda", 1, 30)); // NOI18N
        jLabel5.setText("FIRST NAME             :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 110, 310, 50);

        jLabel6.setFont(new java.awt.Font("Vrinda", 1, 30)); // NOI18N
        jLabel6.setText("LAST NAME              :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 170, 310, 50);

        jLabel8.setFont(new java.awt.Font("Vrinda", 1, 30)); // NOI18N
        jLabel8.setText("USER NAME             :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 230, 310, 50);

        jLabel9.setFont(new java.awt.Font("Vrinda", 1, 30)); // NOI18N
        jLabel9.setText("PASSWORD             :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 290, 310, 50);

        first.setBackground(new java.awt.Color(108, 122, 137));
        first.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        first.setForeground(new java.awt.Color(228, 241, 254));
        jPanel1.add(first);
        first.setBounds(350, 110, 390, 50);

        last.setBackground(new java.awt.Color(108, 122, 137));
        last.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        last.setForeground(new java.awt.Color(228, 241, 254));
        jPanel1.add(last);
        last.setBounds(350, 170, 390, 50);

        user.setBackground(new java.awt.Color(108, 122, 137));
        user.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        user.setForeground(new java.awt.Color(228, 241, 254));
        jPanel1.add(user);
        user.setBounds(350, 230, 390, 50);

        repassword.setBackground(new java.awt.Color(108, 122, 137));
        repassword.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        repassword.setForeground(new java.awt.Color(228, 241, 254));
        jPanel1.add(repassword);
        repassword.setBounds(350, 350, 390, 50);

        password.setBackground(new java.awt.Color(108, 122, 137));
        password.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        password.setForeground(new java.awt.Color(228, 241, 254));
        jPanel1.add(password);
        password.setBounds(350, 290, 390, 50);

        chek.setBackground(new java.awt.Color(108, 122, 137));
        chek.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        chek.setForeground(new java.awt.Color(228, 241, 254));
        chek.setText("SHOW PASSWORD");
        chek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chekActionPerformed(evt);
            }
        });
        jPanel1.add(chek);
        chek.setBounds(350, 410, 180, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Project images\\97.jpeg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 820, 640);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 840, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String fName=first.getText();
        String lName=last.getText();
        String uName=user.getText();
        String pass=String.valueOf(password.getPassword());
        String repass=String.valueOf(repassword.getPassword());
        
        try{
        if(uName.equals("")){
            JOptionPane.showMessageDialog(null,"Enter User Name");
        }
        else if(pass.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Your Password");
        }
        else if(!pass.equals(repass)){
            JOptionPane.showMessageDialog(null,"Retype your password");
        }
        else{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/my_connection?zeroDateTimeBehavior=convertToNull","root","");
        ResultSet rs=null;
        String query="INSERT INTO register values('"+fName+"','"+lName+"','"+uName+"','"+pass+"','"+repass+"')";
        Statement st=con.createStatement();
        int rt=st.executeUpdate(query);
        if(rt==1){
             JOptionPane.showMessageDialog(null,"Register Successfully");
             Login_page rgf=new Login_page();
             rgf.setVisible(true);
             rgf.pack();
             rgf.setLocationRelativeTo(null);
             Toolkit tk=Toolkit.getDefaultToolkit();
                int xsize=910;
                int ysize=715;
                rgf.setSize(xsize,ysize);
             rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
             this.dispose();
        }
        }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Error"+ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        Login_page rgf=new Login_page();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        Toolkit tk=Toolkit.getDefaultToolkit();
            int xsize=910;
            int ysize=715;
            rgf.setSize(xsize,ysize);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseClicked

    private void chekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chekActionPerformed
        if(chek.isSelected()){
            password.setEchoChar((char)0);
            repassword.setEchoChar((char)0);
        }
        else{
            password.setEchoChar('*');
            repassword.setEchoChar('*');
        }// TODO add your handling code here:
    }//GEN-LAST:event_chekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton chek;
    private javax.swing.JTextField first;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField last;
    private javax.swing.JPasswordField password;
    private javax.swing.JPasswordField repassword;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
