/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sports_Project;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Sponsors extends javax.swing.JFrame {
        DefaultTableModel dtm = new DefaultTableModel();
    /**
     * Creates new form Sponsors
     */
    public Sponsors() {
        this.setResizable(false);
        initComponents();
             int xsize=1650;
             int ysize=956;
             this.setSize(xsize,ysize);
             
        
        try{            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/my_connection?zeroDateTimeBehavior=convertToNull","root","");
            String query="select * from sponsors";
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(query);
            dtm.addColumn("Sponsor_id");
            dtm.addColumn("Name");
            dtm.addColumn("Email_id");
            dtm.addColumn("Contract");
            dtm.addColumn("Category");
            dtm.addColumn("Sponsored_Team");
            while(rs.next()){
                Object[] u1={rs.getString("Sponsor_id"),rs.getString("Name"),rs.getString("Email_id"),rs.getString("Contract"),rs.getString("Category"),rs.getString("Sponsored_Team")};
                dtm.addRow(u1);
            }
            
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Error"+ex); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        contract = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tName = new javax.swing.JTextField();
        academy = new javax.swing.JRadioButton();
        team = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("     ACADEMIC SPONSOR");
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 51));
        jLabel1.setText("                        HYDRA SPORTS ACADEMY");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(5, 5, 1598, 67);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Academy SPONSORS    :-");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(23, 95, 436, 70);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("HOME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(578, 108, 110, 40);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("LOGOUT");
        jPanel1.add(jButton2);
        jButton2.setBounds(820, 108, 110, 40);

        jButton3.setFont(new java.awt.Font("Vijaya", 0, 24)); // NOI18N
        jButton3.setText("ADD SPONSORS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(554, 802, 401, 61);

        jButton5.setFont(new java.awt.Font("Vijaya", 0, 24)); // NOI18N
        jButton5.setText("REMOVE SPONSORS");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(1097, 802, 400, 60);

        jButton6.setFont(new java.awt.Font("Vijaya", 0, 24)); // NOI18N
        jButton6.setText("UPDATE SPONSORS");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(71, 805, 402, 55);

        jTable1.setModel(dtm);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(288, 172, 1123, 402);

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setText("ENTER SPONSOR NAME           :");
        jLabel10.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jLabel10ComponentHidden(evt);
            }
        });
        jPanel1.add(jLabel10);
        jLabel10.setBounds(823, 591, 368, 56);

        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setText("ENTER SPONSOR  E-mail ID     :");
        jLabel11.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jLabel11ComponentHidden(evt);
            }
        });
        jPanel1.add(jLabel11);
        jLabel11.setBounds(23, 656, 368, 55);

        jLabel12.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 0));
        jLabel12.setText("CONTRACT DETAILS                  :");
        jLabel12.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jLabel12ComponentHidden(evt);
            }
        });
        jPanel1.add(jLabel12);
        jLabel12.setBounds(823, 666, 368, 32);

        jLabel13.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 0));
        jLabel13.setText("SPONSORED CATEGORY          :");
        jLabel13.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jLabel13ComponentHidden(evt);
            }
        });
        jPanel1.add(jLabel13);
        jLabel13.setBounds(23, 723, 368, 55);

        jLabel14.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 0));
        jLabel14.setText("ENTER SPONSOR ID                   :");
        jLabel14.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jLabel14ComponentHidden(evt);
            }
        });
        jPanel1.add(jLabel14);
        jLabel14.setBounds(23, 594, 368, 50);

        email.setBackground(new java.awt.Color(108, 122, 137));
        email.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        email.setForeground(new java.awt.Color(228, 241, 254));
        jPanel1.add(email);
        email.setBounds(396, 657, 402, 56);

        id.setBackground(new java.awt.Color(108, 122, 137));
        id.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        id.setForeground(new java.awt.Color(228, 241, 254));
        jPanel1.add(id);
        id.setBounds(396, 593, 402, 56);

        contract.setBackground(new java.awt.Color(108, 122, 137));
        contract.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        contract.setForeground(new java.awt.Color(228, 241, 254));
        jPanel1.add(contract);
        contract.setBounds(1196, 656, 402, 56);

        name.setBackground(new java.awt.Color(108, 122, 137));
        name.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        name.setForeground(new java.awt.Color(228, 241, 254));
        jPanel1.add(name);
        name.setBounds(1196, 593, 402, 56);

        jLabel15.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 0));
        jLabel15.setText("TEAM NAME                                 :");
        jLabel15.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jLabel15ComponentHidden(evt);
            }
        });
        jPanel1.add(jLabel15);
        jLabel15.setBounds(823, 720, 368, 61);

        tName.setBackground(new java.awt.Color(108, 122, 137));
        tName.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        tName.setForeground(new java.awt.Color(228, 241, 254));
        jPanel1.add(tName);
        tName.setBounds(1196, 724, 402, 56);

        academy.setText("ACADEMY");
        academy.setBorder(new javax.swing.border.MatteBorder(null));
        academy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                academyActionPerformed(evt);
            }
        });
        jPanel1.add(academy);
        academy.setBounds(599, 725, 194, 59);

        team.setText("TEAM");
        team.setBorder(new javax.swing.border.MatteBorder(null));
        team.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamActionPerformed(evt);
            }
        });
        jPanel1.add(team);
        team.setBounds(396, 727, 196, 55);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Project images\\117.jpg")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 10, 1600, 880);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 1620, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel15ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel15ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15ComponentHidden

    private void jLabel14ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel14ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14ComponentHidden

    private void jLabel13ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel13ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13ComponentHidden

    private void jLabel12ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel12ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12ComponentHidden

    private void jLabel11ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel11ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11ComponentHidden

    private void jLabel10ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel10ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10ComponentHidden

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String Sponsor_id =id.getText();
        String Name=name.getText();
        String Email_id=email.getText();
        String Contract=contract.getText();
        String Sponsored_Team=tName.getText();
        if(Sponsor_id.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Sponsor Id");
        }
        else if(Name.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Sponsor Name");
        }
        else if(email.equals("")){
            JOptionPane.showMessageDialog(null,"Enter your Email");
        }
        else if(contract.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Contarct Time");
        }
        else if(tName.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Team Name");
        }
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/my_connection?zeroDateTimeBehavior=convertToNull","root","");
            ResultSet rs=null;
            int candidateId=0;
            String query="DELETE FROM  sponsors WHERE(Sponsor_id='"+Sponsor_id+"')";
            Statement st=con.createStatement();
            int rowAffected=st.executeUpdate(query);
            JOptionPane.showMessageDialog(null,rowAffected+"SPONSOR DELETED SUCCESSFULLY");
            id.setText(" ");
            name.setText(" ");
            email.setText(" ");
            contract.setText(" ");
            tName.setText(" ");
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Error"+ex);
        }   // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String Sponsor_id =id.getText();
        String Name=name.getText();
        String Email_id=email.getText();
        String Contract=contract.getText();
        String Sponsored_Team=tName.getText();
        String Category;
        if(team.isSelected()){
            Category="TEAM";
        }
        else{
            Category="ACADEMY";
        }
        if(Sponsor_id.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Sponsor Id");
        }
        else if(Name.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Sponsor Name");
        }
        else if(email.equals("")){
            JOptionPane.showMessageDialog(null,"Enter your Email");
        }
        else if(contract.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Contarct Time");
        }
        else if(Category.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Category");
        }
        else if(tName.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Team Name");
        }
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/my_connection?zeroDateTimeBehavior=convertToNull","root","");
            ResultSet rs=null;
            int candidateId=0;
            String query="INSERT INTO sponsors values('"+Sponsor_id+"','"+Name+"','"+Email_id+"','"+Contract+"','"+Category+"','"+Sponsored_Team+"')";
            Statement st=con.createStatement();
            int rowAffected=st.executeUpdate(query);
            JOptionPane.showMessageDialog(null,Name+" Sponsor Added");
            id.setText(" ");
            name.setText(" ");
            email.setText(" ");
            contract.setText(" ");
            tName.setText(" ");
            team.setSelected(false);
            academy.setSelected(false);
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Error"+ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Sports_System SS=new Sports_System();
        SS.setVisible(true);
        SS.pack();
        SS.setLocationRelativeTo(null);
        Toolkit tk=Toolkit.getDefaultToolkit();
        int xsize=947;
        int ysize=707;
        SS.setSize(xsize,ysize);
        SS.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void teamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamActionPerformed
        if(team.isSelected()){
                academy.setSelected(false);
            }        // TODO add your handling code here:
    }//GEN-LAST:event_teamActionPerformed

    private void academyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_academyActionPerformed
        if(academy.isSelected()){
                team.setSelected(false);
            }        // TODO add your handling code here:
    }//GEN-LAST:event_academyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sponsors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sponsors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sponsors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sponsors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sponsors().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton academy;
    private javax.swing.JTextField contract;
    private javax.swing.JTextField email;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField tName;
    private javax.swing.JRadioButton team;
    // End of variables declaration//GEN-END:variables
}
