/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sports_Project;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author user
 */
public class Sports extends javax.swing.JFrame {
    DefaultTableModel dtm1 = new DefaultTableModel();

    /**
     * Creates new form Sports
     */
    public Sports() {
        this.setResizable(false);
        initComponents();
        Toolkit tk=Toolkit.getDefaultToolkit();
                int xsize=939;
                int ysize=816;
                this.setSize(xsize,ysize);
                
        try{            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/my_connection?zeroDateTimeBehavior=convertToNull","root","");
            String query="select * from sports";
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(query);
            dtm1.addColumn("Sports_id");
            dtm1.addColumn("Name");
            dtm1.addColumn("Fee");
            dtm1.addColumn("Timing");
            while(rs.next()){
                Object[] u1={rs.getString("Sports_id"),rs.getString("Name"),rs.getInt("Fee"),rs.getString("Timing")};
                dtm1.addRow(u1);
            }
            
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Error"+ex); 
        }         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        SId3 = new javax.swing.JTextField();
        SName = new javax.swing.JTextField();
        SFee = new javax.swing.JTextField();
        STime = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("     ACADEMIC SPORTS");
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("      HYDRA SPORTS ACADEMY");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(5, 5, 900, 92);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setText("Academy Sports :-");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(17, 104, 533, 78);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setModel(dtm1);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(50, 200, 778, 142);

        jButton6.setFont(new java.awt.Font("Vijaya", 0, 24)); // NOI18N
        jButton6.setText("ADD SPORTS");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(34, 618, 347, 56);

        jButton3.setFont(new java.awt.Font("Vijaya", 0, 24)); // NOI18N
        jButton3.setText("UPDATE SPORTS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(250, 690, 347, 56);

        jButton4.setFont(new java.awt.Font("Vijaya", 0, 24)); // NOI18N
        jButton4.setText("REMOVE SPORTS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(460, 620, 346, 56);

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("ENTER SPORTS ID            :");
        jLabel10.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jLabel10ComponentHidden(evt);
            }
        });
        jPanel1.add(jLabel10);
        jLabel10.setBounds(17, 349, 320, 56);

        jLabel13.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("ENTER SPORTS NAME    :");
        jLabel13.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jLabel13ComponentHidden(evt);
            }
        });
        jPanel1.add(jLabel13);
        jLabel13.setBounds(17, 414, 320, 57);

        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("ENTER SPORTS FEES       :");
        jLabel11.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jLabel11ComponentHidden(evt);
            }
        });
        jPanel1.add(jLabel11);
        jLabel11.setBounds(17, 481, 320, 56);

        jLabel12.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("ENTER SPORTS TIME      :");
        jLabel12.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jLabel12ComponentHidden(evt);
            }
        });
        jPanel1.add(jLabel12);
        jLabel12.setBounds(17, 545, 320, 50);

        SId3.setEditable(false);
        SId3.setBackground(new java.awt.Color(108, 122, 137));
        SId3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        SId3.setForeground(new java.awt.Color(228, 241, 254));
        jPanel1.add(SId3);
        SId3.setBounds(342, 351, 402, 56);

        SName.setBackground(new java.awt.Color(108, 122, 137));
        SName.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        SName.setForeground(new java.awt.Color(228, 241, 254));
        jPanel1.add(SName);
        SName.setBounds(342, 416, 402, 56);

        SFee.setBackground(new java.awt.Color(108, 122, 137));
        SFee.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        SFee.setForeground(new java.awt.Color(228, 241, 254));
        jPanel1.add(SFee);
        SFee.setBounds(342, 479, 402, 56);

        STime.setBackground(new java.awt.Color(108, 122, 137));
        STime.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        STime.setForeground(new java.awt.Color(228, 241, 254));
        jPanel1.add(STime);
        STime.setBounds(342, 544, 402, 56);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("HOME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(577, 129, 110, 40);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("LOGOUT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(779, 129, 110, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\Project images\\114.jpg")); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 10, 890, 740);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 910, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String Sports_id =SName.getText();
        String Name=SName.getText();
        String Fee=SFee.getText();
        String Timings=STime.getText();
        if(Sports_id.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Sports Id");
        }
        else if(Name.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Sports Name");
        }
        else if(Fee.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Fee of Sport");
        }
        else if(Timings.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Time of your sport");
        }
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/my_connection?zeroDateTimeBehavior=convertToNull","root","");
            ResultSet rs=null;
            int candidateId=0;
            String query="INSERT INTO sports values('"+Sports_id+"','"+Name+"','"+Fee+"','"+Timings+"')";
            Statement st=con.createStatement();
            int rowAffected=st.executeUpdate(query);
            JOptionPane.showMessageDialog(null,rowAffected+"New Sport Added");
            SName.setText(" ");
            SName.setText(" ");
            SFee.setText(" ");
            STime.setText(" ");
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Error"+ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String Sports_id =SName.getText();
        String Name=SName.getText();
        String Fee=SFee.getText();
        String Timings=STime.getText();
        if(Sports_id.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Sports Id");
        }
        else if(Name.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Sports Name");
        }
        else if(Fee.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Fee of Sport");
        }
        else if(Timings.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Time of your sport");
        }
        int response=JOptionPane.showConfirmDialog(this,"Are you sure you want to delete Record","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(response==JOptionPane.YES_OPTION){
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/my_connection?zeroDateTimeBehavior=convertToNull","root","");
                ResultSet rs=null;
                int candidateId=0;
                String query="UPDATE `sports` SET('Sports_id'='"+Sports_id+"','Name'='"+Name+"','Fee'='"+Fee+"','Timings'='"+Timings+"') WHERE(Sports_id='"+Sports_id+"')";
                Statement st=con.createStatement();
                int rowAffected=st.executeUpdate(query);
                JOptionPane.showMessageDialog(null,rowAffected+"Record updated Successfully");
                SName.setText(" ");
                SName.setText(" ");
                SFee.setText(" ");
                STime.setText(" ");
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(null,"Error"+ex);
            } }
            else if(response==JOptionPane.NO_OPTION){
                Sports AS=new Sports();
                AS.setVisible(true);
                AS.pack();
                AS.setLocationRelativeTo(null);
                Toolkit tk=Toolkit.getDefaultToolkit();
                int xsize=1140;
                int ysize=1080;
                AS.setSize(xsize,ysize);
                AS.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                this.dispose();
            }
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String Sports_id =SName.getText();
        String Name=SName.getText();
        String Fee=SFee.getText();
        String Timings=STime.getText();
        if(Sports_id.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Sports Id");
        }
        else if(Name.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Sports Name");
        }
        else if(Fee.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Fee of Sport");
        }
        else if(Timings.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Time of your sport");
        }
        int response=JOptionPane.showConfirmDialog(this,"Are you sure you want to delete Record","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(response==JOptionPane.YES_OPTION){
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/my_connection?zeroDateTimeBehavior=convertToNull","root","");
                ResultSet rs=null;
                int candidateId=0;
                String query="DELETE FROM sports Where(Sports_id='"+Sports_id+"' AND Name='"+Name+"')";
                Statement st=con.createStatement();
                int rowAffected=st.executeUpdate(query);
                JOptionPane.showMessageDialog(null,rowAffected+"Record Deleted Successfully");
                SName.setText(" ");
                SName.setText(" ");
                SFee.setText(" ");
                STime.setText(" ");
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(null,"Error"+ex);
            }}
            else if(response==JOptionPane.NO_OPTION){
                Sports AS=new Sports();
                AS.setVisible(true);
                AS.pack();
                AS.setLocationRelativeTo(null);
                Toolkit tk=Toolkit.getDefaultToolkit();
                int xsize=1140;
                int ysize=1080;
                AS.setSize(xsize,ysize);
                AS.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                this.dispose();
            }          // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel10ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel10ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10ComponentHidden

    private void jLabel13ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel13ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13ComponentHidden

    private void jLabel11ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel11ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11ComponentHidden

    private void jLabel12ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel12ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12ComponentHidden

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Sports_System SS=new Sports_System();
        SS.setVisible(true);
        SS.pack();
        SS.setLocationRelativeTo(null);
        Toolkit tk=Toolkit.getDefaultToolkit();
        int xsize=947;
        int ysize=707;
        SS.setSize(xsize,ysize);
        SS.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         Login_page rgf=new Login_page();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        Toolkit tk=Toolkit.getDefaultToolkit();
                int xsize=910;
                int ysize=715;
                rgf.setSize(xsize,ysize);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SFee;
    private javax.swing.JTextField SId3;
    private javax.swing.JTextField SName;
    private javax.swing.JTextField STime;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
